services:
  nginx:
    image: nginx:v1.0
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - CRED_PATH
        - CRED_CERT
        - CRED_KEY
        - COUNTRY
        - STATE
        - LOCALITY
        - ORGANIZATION
        - ORG_UNIT
        - COMMON_NAME
    container_name: nginx
    ports:
      - "443:443"
    restart: unless-stopped
    depends_on:
      - wordpress
    networks:
      - inception-network
    volumes:
      - v_web:/var/www/html

  wordpress:
    image: wordpress:v1.0
    build: requirements/wordpress/.
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception-network
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - v_web:/var/www/html
    env_file:
      - .env

  mariadb:
    image: mariadb:v1.0
    build: requirements/mariadb/.
    container_name: mariadb
    restart: unless-stopped
    networks:
      - inception-network
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - v_db:/var/lib/mysql
      - ./requirements/mariadb/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    env_file:
      - .env

volumes:
  v_web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pauldos-/data/wordpress

  v_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pauldos-/data/mariadb

networks:
  inception-network:
    driver: bridge
